version: '3.4'
services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/kubo:release
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs api
      - "8081:8080" # ipfs gateway
    volumes:
      - ./private/var/services/librum/ipfs/ipfs0:/data/ipfs
  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: "34a320169537634ea2b304eac9970d0203d94b320f82f09d89e96c94e2c7950c" # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "9094:9094" # http api
      - "9095:9095" # proxy api
      - "9096:9096" # cluster swarm, other peers connect via this port
    volumes:
      - ./private/var/services/librum/ipfs/cluster0:/data/ipfs-cluster

  ipfs1:
    container_name: ipfs1
    image: ipfs/kubo:release
    volumes:
      - ./private/var/services/librum/ipfs/ipfs1:/data/ipfs
  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: "34a320169537634ea2b304eac9970d0203d94b320f82f09d89e96c94e2c7950c"
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "9097:9097" # http api
      - "9098:9098" # proxy api
      - "9099:9099" # cluster swarm, other peers connect via this port
    volumes:
      - ./private/var/services/librum/ipfs/cluster1:/data/ipfs-cluster
    command:
      - "daemon --bootstrap  /ip4/172.23.0.3/tcp/9096/p2p/12D3KooWLLUsXWpQZsrKG5NMx8THqXtNaDEcXMwthXNbnKnwWFHn"

  ipfs2:
    container_name: ipfs2
    image: ipfs/kubo:release
    volumes:
      - ./private/var/services/librum/ipfs/ipfs2:/data/ipfs
  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs2
    environment:
      CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: "34a320169537634ea2b304eac9970d0203d94b320f82f09d89e96c94e2c7950c"
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "9100:9100" # http api
      - "9101:9101" # proxy api
      - "9102:9102" # cluster swarm, other peers connect via this port
    volumes:
      - ./private/var/services/librum/ipfs/cluster2:/data/ipfs-cluster
    command:
      - "daemon --bootstrap  /ip4/172.23.0.3/tcp/9096/p2p/12D3KooWLLUsXWpQZsrKG5NMx8THqXtNaDEcXMwthXNbnKnwWFHn"
